soccer_analytics: 
  target: dev
  outputs:
    dev:
      type: snowflake
      account: fnutubx-kab87271 # Snowflake account identifier
      user: dbt_user
      password: "{{ env_var('DBT_PASSWORD') }}" # Using environment variable for security
      role: TRANSFORM_ROLE
      database: SOCCER_DB
      warehouse: SOCCER_WH
      schema: dev_schema
      threads: 4
      client_session_keep_alive: False