-- 1. Set the role to ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- 2. Create the transform role and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM_ROLE;
GRANT ROLE TRANSFORM_ROLE TO ROLE ACCOUNTADMIN;

-- 3. Create a default warehouse and grant access
CREATE OR REPLACE WAREHOUSE SOCCER_WH 
  WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;
GRANT ALL ON WAREHOUSE SOCCER_WH TO ROLE TRANSFORM_ROLE;

-- 4. Create a database and schema for the soccer project
CREATE DATABASE IF NOT EXISTS SOCCER_DB;
CREATE SCHEMA IF NOT EXISTS SOCCER_DB.RAW;

-- 5. Grant comprehensive permissions (including FUTURE creations) to the role
GRANT ALL ON DATABASE SOCCER_DB TO ROLE TRANSFORM_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE SOCCER_DB TO ROLE TRANSFORM_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE SOCCER_DB TO ROLE TRANSFORM_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA SOCCER_DB.RAW TO ROLE TRANSFORM_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA SOCCER_DB.RAW TO ROLE TRANSFORM_ROLE;

-- 6. Create the dbt user and assign it to the transform role
CREATE USER IF NOT EXISTS dbt_user
  PASSWORD = '***' -- Masked for security and Git version control
  LOGIN_NAME = 'dbt_user'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE = 'SOCCER_WH'
  DEFAULT_ROLE = 'TRANSFORM_ROLE'
  DEFAULT_NAMESPACE = 'SOCCER_DB.RAW'
  COMMENT = 'Service user for dbt data transformations';

-- 7. Assign the user to the transform role
GRANT ROLE TRANSFORM_ROLE TO USER dbt_user;